SECRET_KEY= b'azertyuiop1234567890'
ENV='development'
TEMPLATES_AUTO_RELOAD = 1
SQLALCHEMY_DATABASE_URI = 'sqlite:///todolist.db'
SQLALCHEMY_TRACK_MODIFICATIONS = 0
DEBUG_TB_INTERCEPT_REDIRECTS = False
